version: '3'
services:
  app:
    build: .
    container_name: 'feature_service'
    volumes:
      - .:/app
    ports:
      - "8001:8001"

  redis:
    image: redis
    container_name: 'redis'
    ports:
      - "6379:6379"
